#!/usr/bin/env python3

def main():
    
    import os
    import sys
    
    from analyzer import Analyzer
    from termcolor import colored
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile twitter_handle")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # Fftch twitter timeline
    timeline = helpers.get_user_timeline(sys.argv[1], 100)
    
    # iterate through tweets
    for tweet in timeline:
        
        # run analyzer
        score = analyzer.analyze(tweet)
        
        #output
        if score > 0.0:
            print(colored(score, "green"), colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), colored(tweet, "red"))
        else:
            print(colored(score, "yellow"), colored(tweet, "yellow"))
    
if __name__ == "__main__":
    main()
